package com.model;

/**
 * TBaoming generated by MyEclipse Persistence Tools
 */

public class TBaoming implements java.io.Serializable
{

	// Fields

	private Integer baomingId;

	private Integer catelogId;

	private Integer yundongyuanId;

	private String baomingShijian;
	
	private String baomingZhuangtai;//"shenpizhong","pass"."fail"
	
	private String catelogName;
	
	private String yundongyuanName;

	// Constructors

	/** default constructor */
	public TBaoming()
	{
	}

	/** full constructor */
	public TBaoming(Integer catelogId, Integer yundongyuanId,
			String baomingShijian)
	{
		this.catelogId = catelogId;
		this.yundongyuanId = yundongyuanId;
		this.baomingShijian = baomingShijian;
	}

	// Property accessors

	public Integer getBaomingId()
	{
		return this.baomingId;
	}

	public void setBaomingId(Integer baomingId)
	{
		this.baomingId = baomingId;
	}

	public Integer getCatelogId()
	{
		return this.catelogId;
	}

	public void setCatelogId(Integer catelogId)
	{
		this.catelogId = catelogId;
	}

	public String getBaomingZhuangtai()
	{
		return baomingZhuangtai;
	}

	public void setBaomingZhuangtai(String baomingZhuangtai)
	{
		this.baomingZhuangtai = baomingZhuangtai;
	}

	public String getCatelogName()
	{
		return catelogName;
	}

	public void setCatelogName(String catelogName)
	{
		this.catelogName = catelogName;
	}

	public Integer getYundongyuanId()
	{
		return this.yundongyuanId;
	}

	public void setYundongyuanId(Integer yundongyuanId)
	{
		this.yundongyuanId = yundongyuanId;
	}

	public String getBaomingShijian()
	{
		return this.baomingShijian;
	}

	public void setBaomingShijian(String baomingShijian)
	{
		this.baomingShijian = baomingShijian;
	}

	public String getYundongyuanName()
	{
		return yundongyuanName;
	}

	public void setYundongyuanName(String yundongyuanName)
	{
		this.yundongyuanName = yundongyuanName;
	}

}