package com.model;

/**
 * TYundongyuan generated by MyEclipse Persistence Tools
 */

public class TYundongyuan implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String loginname;

	private String loginpw;

	private String xuehao;

	private String banji;

	private String name;

	private String sex;

	private String age;

	private String tel;

	private String shengtizhuangkuang;

	private String del;

	// Constructors

	/** default constructor */
	public TYundongyuan()
	{
	}

	/** full constructor */
	public TYundongyuan(String loginname, String loginPw, String xuehao,
			String banji, String name, String sex, String age, String tel,
			String shengtizhuangkuang, String del)
	{
		this.loginname = loginname;
		this.xuehao = xuehao;
		this.banji = banji;
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.tel = tel;
		this.shengtizhuangkuang = shengtizhuangkuang;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getLoginname()
	{
		return this.loginname;
	}

	public void setLoginname(String loginname)
	{
		this.loginname = loginname;
	}


	public String getLoginpw()
	{
		return loginpw;
	}

	public void setLoginpw(String loginpw)
	{
		this.loginpw = loginpw;
	}

	public String getXuehao()
	{
		return this.xuehao;
	}

	public void setXuehao(String xuehao)
	{
		this.xuehao = xuehao;
	}

	public String getBanji()
	{
		return this.banji;
	}

	public void setBanji(String banji)
	{
		this.banji = banji;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getSex()
	{
		return this.sex;
	}

	public void setSex(String sex)
	{
		this.sex = sex;
	}

	public String getAge()
	{
		return this.age;
	}

	public void setAge(String age)
	{
		this.age = age;
	}

	public String getTel()
	{
		return this.tel;
	}

	public void setTel(String tel)
	{
		this.tel = tel;
	}

	public String getShengtizhuangkuang()
	{
		return this.shengtizhuangkuang;
	}

	public void setShengtizhuangkuang(String shengtizhuangkuang)
	{
		this.shengtizhuangkuang = shengtizhuangkuang;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}